spring:
  application:
    name: ricettario-be
  datasource:
    url: jdbc:postgresql://localhost:5432/db_ricettario
    username: postgres
    password: ricettario
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
jwt:
  secret: r0Q7XA4T4kmXgcEvHUlgka79Kj0E7o4/hPghvyK3l5I=
  expiration: 3600000
